name: Deploy packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages to build'
        default: 'archlinux/* debian/*'
        required: true
        type: string
  push:
    branches:
      - master

jobs:
  deploy-archlinux:
    name: Deploy Arch Linux packages
    uses: ./.github/workflows/deploy-archlinux.yml
    secrets: inherit
    with:
      packages: ${{ inputs.packages }}

  deploy-debian-amd64:
    name: Deploy Debian packages (amd64)
    uses: ./.github/workflows/deploy-debian.yml
    secrets: inherit
    with:
      arch: amd64
      packages: ${{ inputs.packages }}

  deploy-debian-arm64:
    name: Deploy Debian packages (arm64)
    uses: ./.github/workflows/deploy-debian.yml
    secrets: inherit
    with:
      arch: arm64
      packages: ${{ inputs.packages }}
